In [2]:
# Superstore Sales Analysis
# Day 1: Data Loading and Exploration
# Goal: Understand what data we have before we analyze anything

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv(r"C:\Users\stu-tamangn\Documents\github proj 1\superstore-sales-analysis\data\Superstore.csv", encoding='latin-1')
print("Data sucessfully loaded")
print(f"Shape: {df.shape}")

Data sucessfully loaded
Shape: (9994, 21)

In [5]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [7]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [8]:
missing = df.isnull().sum()
print("Missing values per column:")
print(missing[missing > 0])

Missing values per column:
Series([], dtype: int64)

In [9]:
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

Number of duplicate rows: 0

In [10]:
## Day 1 Exploration Questions
Finding out answers of 7 basic questions about the dataset before any analysis.

SyntaxError: invalid syntax (4195529076.py, line 2)

In [ ]:
# How many orders are in this dataset?
print(f"Total rows

In [ ]:
## Day 2: Data Cleaning
Goal: Fix data types, add useful columns, and document all decisions.

In [26]:
print(df['Order Date'].dtype)
print(df['Ship Date'].dtype)
print(df['Order Date'].head)

datetime64[us]
datetime64[us]
<bound method NDFrame.head of 0      2016-11-08
1      2016-11-08
2      2016-06-12
3      2015-10-11
4      2015-10-11
          ...
9989   2014-01-21
9990   2017-02-26
9991   2017-02-26
9992   2017-02-26
9993   2017-05-04
Name: Order Date, Length: 9994, dtype: datetime64[us]>

In [34]:
df['Order Date']=pd.to_datetime(df['Order Date'])
df['Ship Date']=pd.to_datetime(df['Ship Date'])
print(df['Order Date'].dtype)
print(df['Ship Date'].dtype)

datetime64[us]
datetime64[us]

In [28]:
df['Order Month']=df['Order Date'].dt.month
df['Order Year']=df['Order Date'].dt.year
print(df[['Order Date','Order Month', 'Order Year']].head())

  Order Date  Order Month  Order Year
0 2016-11-08           11        2016
1 2016-11-08           11        2016
2 2016-06-12            6        2016
3 2015-10-11           10        2015
4 2015-10-11           10        2015

In [37]:
df['Order Month Name']=df['Order Date'].dt.strftime('%b')
print(df[['Order Date', 'Order Month','Order Month Name']].head(10))

  Order Date  Order Month Order Month Name
0 2016-11-08           11              Nov
1 2016-11-08           11              Nov
2 2016-06-12            6              Jun
3 2015-10-11           10              Oct
4 2015-10-11           10              Oct
5 2014-06-09            6              Jun
6 2014-06-09            6              Jun
7 2014-06-09            6              Jun
8 2014-06-09            6              Jun
9 2014-06-09            6              Jun

In [51]:
#Days to Ship?
#Average days needed to ship the product
#Max days to ship
#min days to ship

df['Days to Ship']=(df['Ship Date']-df['Order Date']).dt.days
print( "Ship days:\n", df['Days to Ship'].head(10))
print(f"Average days to ship: {df['Days to Ship'].mean():.2f} days")
print(f"Max days to ship: {df['Days to Ship'].max()} days")
print(f"Min days to ship: {df['Days to Ship'].min()} days")

Ship days:
 0    3
1    3
2    4
3    7
4    7
5    5
6    5
7    5
8    5
9    5
Name: Days to Ship, dtype: int64
Average days to ship: 3.96 days
Max days to ship: 7 days
Min days to ship: 0 days

In [65]:
#Profit margin
df['Profit Margin']=(df['Profit']/df['Sales'])*100
print(df[['Profit', 'Sales', 'Profit Margin']].head(5))
print(f"Average profit margin per row: {df['Profit Margin'].mean():.2f} %")

     Profit     Sales  Profit Margin
0   41.9136  261.9600          16.00
1  219.5820  731.9400          30.00
2    6.8714   14.6200          47.00
3 -383.0310  957.5775         -40.00
4    2.5164   22.3680          11.25
Average profit margin per row: 12.03 %

In [69]:
print(f"Columns now: {len(df.columns)}")
print(df.columns.tolist())

Columns now: 26
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Order Month', 'Order Year', 'Order Month Name', 'Days to Ship', 'Profit Margin']

In [74]:
#rows
#columns
#missing values
#duplicate rows
#date ranges
#years covered
#average days to ship
print("Final quality data check:")
print(f"Total Rows: {len(df)}")  
print(f"Total Columns: {len(df.columns)}")
print(f"Missing values: {df.isnull().sum().sum()}")
print(f"Duplicate rows: {df.duplicated().sum()}")
print(f"Date ranges from {df['Order Date'].min()} to {df['Order Date'].max()}")
print(f"Years covered: {sorted(df['Order Year'].unique())}")
print(f"Average days to Ship: {df['Days to Ship'].mean():.2f}")

Final quality data check:
Total Rows: 9994
Total Columns: 26
Missing values: 0
Duplicate rows: 0
Date ranges from 2014-01-03 00:00:00 to 2017-12-30 00:00:00
Years covered: [np.int32(2014), np.int32(2015), np.int32(2016), np.int32(2017)]
Average days to Ship: 3.96

In [75]:
df.to_csv('../data/superstore_cleaned.csv', index=False)
print("Cleaned file saved successfully")

Cleaned file saved successfully

In [ ]:
## Day 2 Cleaning Decisions

1. Converted Order Date and Ship Date from object to datetime64
   - Reason: This was needed for time-based analysis (year, month comparision) and calculating days to ship

2. Added Order Month column (numeric)
   - Reason: This is needed for grouping the sales data by month in SQL queries for looking trends

3. Added Order Year column (numeric)
   - Reason: This is needed for year-over-year comparisons

4. Added Month Name column (text abbreviation)
   - Reason: This is more readable labels for charts (visualization)

5. Added Days to Ship column
   - Reason: This measures shipping speed, will use for late shipment analysis

6. Added Profit Margin column
   - Reason: The raw profit alone is misleading without context of sales volume. Hence, we will use Profit margin percentage for analysis

## What I Found
- Average days to ship: [fill in your number]
- Average profit margin per transaction: [fill in your number]%
- Dataset now has 25 columns, all clean, no nulls, no duplicates